-- ================================================================
-- SEED — Produits de démonstration (Dar Chakaf)
-- 64 produits répartis sur les 7 catégories.
-- À exécuter APRÈS db/schema.sql
-- ================================================================

-- ---- salons-modernes ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Aurore', 'Canapé d''angle modulable, tissu chenille, structure en bois massif.', 14900, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'beige', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Marbella', 'Assises basses, lignes droites, revêtement cuir végétal beige sable.', 18500, NULL, 'm', 'disponible', NULL, 'leather', NULL, 'beige', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Kenza', 'Composition 3+2 places, coussins déhoussables, pieds laiton brossé.', 16200, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'grey', 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Riad Contemporain', 'Version modernisée du salon marocain, tissu jacquard et bois d''olivier.', 21000, NULL, 'm', 'disponible', NULL, 'wood', NULL, 'burgundy', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Zenith', 'Design minimaliste, velours côtelé bleu nuit, accoudoirs arrondis.', 19800, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'navy', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Atlas', 'Grand format familial, tissu anti-tâches, coffre de rangement intégré.', 23400, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'grey', 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Oasis', 'Confort enveloppant, couleurs neutres, élégance intemporelle.', 16300, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'beige', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Élégance', 'Minimalisme raffiné, matières nobles, finitions soignées.', 12800, NULL, 'm', 'disponible', NULL, 'leather', NULL, 'grey', 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-modernes'), 'Salon Prestige', 'Luxe discret, cuir italien, structure en bois massif.', 18200, 22000, 'm', 'disponible', NULL, 'leather', NULL, 'burgundy', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', 'Promotion');

-- ---- salons-traditionnels ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Fès', 'Inspiration médina, bois sculpté à la main, tissus traditionnels marocains.', 18000, NULL, 'm', 'disponible', NULL, 'wood', NULL, 'brown', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Artisanat');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Marrakech', 'Élégance ocre, motifs géométriques, confort authentique en tissu jacquard.', 16000, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'beige', 'https://images.unsplash.com/photo-1564813733665-b1996b6de2e3?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Tétouan', 'Artisanat andalou, finitions raffinées, bois précieux et velours profond.', 22000, NULL, 'm', 'disponible', NULL, 'wood', NULL, 'burgundy', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', 'Collection limitée');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Chefchaouen', 'Bleu et blanc, inspiré des montagnes du Rif, élégance méditerranéenne.', 14000, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'navy', 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Rabat', 'Design moderne marocain, lignes épurées, couleurs douces en lin naturel.', 13000, NULL, 'm', 'disponible', NULL, 'fabric', NULL, 'beige', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Casa', 'Élégance urbaine, design contemporain avec touches marocaines en cuir.', 15000, 19000, 'm', 'disponible', NULL, 'leather', NULL, 'brown', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Promotion');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Agadir', 'Ambiance côtière, couleurs sable et blanc, matières naturelles.', 12500, NULL, 'm', 'disponible', NULL, 'wood', NULL, 'beige', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'salons-traditionnels'), 'Salon Meknès', 'Artisanat impérial, boiseries fines, velours bordeaux et or.', 19500, NULL, 'm', 'disponible', NULL, 'wood', NULL, 'burgundy', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', 'Best-seller');

-- ---- tables ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Royale', 'Bois massif, design intemporel, capacité 10 personnes.', 8900, NULL, 'unité', 'disponible', '220 x 100 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Élégance', 'Design contemporain, plateau en verre trempé, pieds en métal laqué.', 5600, NULL, 'unité', 'disponible', '160 x 90 x 76 cm', 'glass', NULL, 'white', 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Oasis', 'Bois d''olivier massif, finition huilée, design organique.', 7200, NULL, 'unité', 'disponible', '180 x 95 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Urban', 'Design industriel, plateau en bois recyclé, pieds en métal noir.', 4800, NULL, 'unité', 'disponible', '140 x 80 x 76 cm', 'metal', NULL, 'dark', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Marbre', 'Plateau en marbre blanc, piètement en laiton brossé, luxe discret.', 12500, NULL, 'unité', 'disponible', '200 x 100 x 76 cm', 'glass', NULL, 'white', 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Rustique', 'Bois massif vieilli, aspect brut, charme authentique.', 6500, 8200, 'unité', 'disponible', '180 x 90 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', 'Promotion');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Ronde Méditerranée', 'Table ronde en bois massif, idéale pour les dîners en famille.', 5900, NULL, 'unité', 'disponible', 'Ø 140 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Loft', 'Design minimaliste, plateau en chêne massif, pieds en acier.', 7800, NULL, 'unité', 'disponible', '220 x 95 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tables'), 'Table Carrée Contemporaine', 'Table carrée en bois massif, finition mate, design scandinave.', 5200, NULL, 'unité', 'disponible', '120 x 120 x 76 cm', 'wood', NULL, 'wood', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', 'Nouveau');

-- ---- decorations ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Miroir Ovation', 'Miroir mural en laiton martelé, finition dorée.', 2400, NULL, 'unité', 'active', '80 x 120 cm', NULL, 'mirror', NULL, 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Vase Majorelle', 'Vase en céramique émaillée, motif berbère.', 890, NULL, 'unité', 'active', 'H 45 cm', NULL, 'vase', NULL, 'https://images.unsplash.com/photo-1564813733665-b1996b6de2e3?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Lustre Orient', 'Lustre en laiton et verre soufflé, 12 lumières.', 3200, NULL, 'unité', 'active', 'Ø 80 cm', NULL, 'lamp', NULL, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Sculpture Équilibre', 'Sculpture en bronze sur socle en marbre.', 1800, NULL, 'unité', 'active', 'H 55 cm', NULL, 'sculpture', NULL, 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Applique Murale', 'Applique en laiton brossé, abat-jour en lin.', 550, NULL, 'unité', 'active', '30 x 45 cm', NULL, 'lamp', NULL, 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Miroir Soleil', 'Miroir rond à rayons, structure en fer forgé.', 1600, NULL, 'unité', 'active', 'Ø 60 cm', NULL, 'mirror', NULL, 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Vase Amber', 'Vase en verre soufflé, couleur ambre.', 650, NULL, 'unité', 'active', 'H 30 cm', NULL, 'vase', NULL, 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'decorations'), 'Bougeoir Trio', 'Set de 3 bougeoirs en laiton, hauteurs variables.', 420, 590, 'unité', 'active', 'H 12-18-24 cm', NULL, 'sculpture', NULL, 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', 'Promotion');

-- ---- meubles-tv ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Moderne', 'Bois laqué, rangements intégrés, design épuré.', 4200, NULL, 'unité', 'active', '180 x 45 x 50 cm', NULL, 'modern', NULL, 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Flottant', 'Design suspendu, structure en bois massif, finition mate.', 5600, NULL, 'unité', 'active', '200 x 40 x 30 cm', NULL, 'floating', NULL, 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Classique', 'Bois sculpté, finition cirée, élégance intemporelle.', 6800, NULL, 'unité', 'active', '190 x 50 x 60 cm', NULL, 'classic', NULL, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Contemporain', 'Portes coulissantes, rangements modulables, design minimal.', 4900, NULL, 'unité', 'active', '220 x 45 x 50 cm', NULL, 'modern', NULL, 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Design', 'Structure en chêne massif, pieds en laiton, luxe discret.', 7800, NULL, 'unité', 'active', '160 x 42 x 55 cm', NULL, 'modern', NULL, 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'meubles-tv'), 'Meuble TV Compact', 'Idéal pour petits espaces, rangement optimisé.', 3200, NULL, 'unité', 'active', '120 x 40 x 45 cm', NULL, 'floating', NULL, 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', NULL);

-- ---- couloirs ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Console Entrée', 'Bois massif, miroir intégré, rangement discret pour vos clés et accessoires.', 3600, NULL, 'unité', 'active', '100 x 40 x 80 cm', 'wood', 'console', NULL, 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Miroir Grand Format', 'Miroir sur pied, structure en bois sculpté, élégance intemporelle.', 2800, NULL, 'unité', 'active', '80 x 180 cm', 'wood', 'mirror', NULL, 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Porte-manteau Design', 'Structure en métal et bois, 5 patères, idéal pour les entrées modernes.', 1200, NULL, 'unité', 'active', 'H 180 cm', 'metal', 'rack', NULL, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Table d''Entrée Marbre', 'Table basse pour entrée, plateau en marbre blanc, piètement laiton brossé.', 4200, NULL, 'unité', 'active', '80 x 40 x 76 cm', 'glass', 'console', NULL, 'https://images.unsplash.com/photo-1564813733665-b1996b6de2e3?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Rangement Entrée', 'Meuble de rangement avec tiroirs et étagères, bois massif laqué.', 3200, NULL, 'unité', 'active', '90 x 35 x 90 cm', 'wood', 'storage', NULL, 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Miroir Soleil', 'Miroir rond à rayons en fer forgé, structure dorée.', 1600, NULL, 'unité', 'active', 'Ø 60 cm', 'metal', 'mirror', NULL, 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Console Métal & Verre', 'Design industriel, plateau en verre trempé, pieds en métal noir.', 2200, 2900, 'unité', 'active', '120 x 35 x 76 cm', 'metal', 'console', NULL, 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', 'Promotion');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Porte-manteau Bois Massif', 'Structure en chêne massif, finition huilée, 6 patères.', 1800, NULL, 'unité', 'active', 'H 200 cm', 'wood', 'rack', NULL, 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Banquette Entrée', 'Banquette en bois massif avec rangement intégré, coussin en tissu.', 3800, NULL, 'unité', 'active', '120 x 40 x 48 cm', 'wood', 'storage', NULL, 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Miroir Contemporain', 'Miroir mural design, cadre en bois laqué noir.', 1400, NULL, 'unité', 'active', '60 x 120 cm', 'wood', 'mirror', NULL, 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Console Marocaine', 'Console traditionnelle marocaine, bois sculpté et laiton.', 4800, NULL, 'unité', 'active', '110 x 45 x 85 cm', 'wood', 'console', NULL, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Artisanat');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'couloirs'), 'Rangement Mural', 'Étagère murale avec patères, idéale pour les petits espaces.', 950, NULL, 'unité', 'active', '60 x 20 x 30 cm', 'wood', 'storage', NULL, 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', NULL);

-- ---- tissus ----
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Rideau Velours Bordeaux', 'Velours épais, couleur bordeaux profond, doublure thermique, tombé parfait.', 1200, NULL, 'm', 'active', '280 x 250 cm', NULL, 'velours', 'bordeaux', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Best-seller');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Tissu Lin Naturel', 'Lin 100% naturel, couleur écru, idéal pour voilages et rideaux légers.', 450, NULL, 'm', 'active', '300 x 150 cm', NULL, 'lin', 'beige', 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Rideau Soie Ivoire', 'Soie naturelle, ton ivoire, tombé fluide, brillance subtile.', 1800, NULL, 'm', 'active', '280 x 300 cm', NULL, 'soie', 'beige', 'https://images.unsplash.com/photo-1564813733665-b1996b6de2e3?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Tissu d''Ameublement Jacquard', 'Tissu jacquard, motifs berbères traditionnels, résistant et élégant.', 650, NULL, 'm', 'active', '200 x 140 cm', NULL, 'jacquard', 'gris', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Velours Côtelé Bleu Nuit', 'Velours côtelé, bleu nuit profond, idéal pour rideaux et coussins.', 980, NULL, 'm', 'active', '280 x 140 cm', NULL, 'velours', 'bleu', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Rideau Lin Beige', 'Lin lavé, couleur beige naturel, aspect froissé chic.', 550, NULL, 'm', 'active', '300 x 260 cm', NULL, 'lin', 'beige', 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Tissu Coton Bio', 'Coton biologique, impression géométrique, idéal pour coussins et rideaux.', 380, NULL, 'm', 'active', '280 x 150 cm', NULL, 'coton', 'beige', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Rideau Soie Bordeaux', 'Soie naturelle, couleur bordeaux, finition satinée.', 2100, 2600, 'm', 'active', '280 x 320 cm', NULL, 'soie', 'bordeaux', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop', 'Promotion');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Tissu Velours Vert', 'Velours vert émeraude, doux et dense, pour un intérieur sophistiqué.', 1100, NULL, 'm', 'active', '280 x 140 cm', NULL, 'velours', 'vert', 'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=800&auto=format&fit=crop', 'Nouveau');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Rideau Coton Gris', 'Coton épais, couleur gris perle, doublure occultante.', 420, NULL, 'm', 'active', '280 x 260 cm', NULL, 'coton', 'gris', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?q=80&w=800&auto=format&fit=crop', NULL);
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Tissu Jacquard Marocain', 'Motifs traditionnels marocains, couleurs chaudes, finition premium.', 850, NULL, 'm', 'active', '200 x 140 cm', NULL, 'jacquard', 'bordeaux', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop', 'Artisanat');
INSERT INTO produits (category_id, titre, description, prix, ancien_prix, unite, statut, dimensions, materiau, type, coloris, image_principale, badge) VALUES ((SELECT id FROM categories WHERE slug = 'tissus'), 'Voilage Lin Blanc', 'Voilage en lin, couleur blanc cassé, léger et aérien.', 320, NULL, 'm', 'active', '300 x 280 cm', NULL, 'lin', 'beige', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', NULL);
